// This file was generated by an AI. Do not modify.
require('dotenv').config();
const express = require('express');
const cors = require('cors');
const { GoogleGenerativeAI } = require('@google/generative-ai');

const app = express();
app.use(cors());
app.use(express.json());

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);

app.post('/api/chat', async (req, res) => {
  try {
        const { message, systemPrompt } = req.body;
    const model = genAI.getGenerativeModel({ 
      model: 'gemini-2.0-flash',
      systemInstruction: systemPrompt || 'You are a helpful assistant.',
    });
    const result = await model.generateContent(message);
    const response = await result.response;
    const text = response.text();
    res.send({ message: text });
  } catch (error) {
    console.error(error);
    res.status(500).send({ error: 'Something went wrong' });
  }
});

app.post('/api/calculate', async (req, res) => {
  try {
    const { expression } = req.body;
    const model = genAI.getGenerativeModel({ 
      model: 'gemini-2.0-flash',
      systemInstruction: 'You are a calculator. You can only return the result of the calculation. Do not explain how you got the result. Do not say anything else.',
    });
    const result = await model.generateContent(expression);
    const response = await result.response;
    const text = response.text();
    res.send({ result: text });
  } catch (error) {
    console.error(error);
    res.status(500).send({ error: 'Something went wrong' });
  }
});

const PORT = process.env.PORT || 5000;

app.listen(PORT, () => {
  console.log(`Server is running on port ${PORT}`);
});