// This file was generated by an AI. Do not modify.
import React, { useState, useEffect } from 'react';
import './App.css';
import Calculator from './Calculator';

// AI-generated inspirational quote
const quotes = [
  '"The only way to do great work is to love what you do." - AI Steve Jobs',
  '"The future belongs to those who believe in the beauty of their AI-generated dreams." - AI Eleanor Roosevelt',
  '"Success is not final, failure is not fatal: it is the courage to continue that counts." - AI Winston Churchill',
  '"The only thing that stands between you and your dream is the will to try and the belief that it is actually possible." - AI Joel Brown',
  '"The best way to predict the future is to invent it, preferably with a neural network." - AI Alan Kay',
  '"I have not failed. I\'ve just found 10,000 ways that won\'t work, and my AI is still learning." - AI Thomas Edison',
  '"Your time is limited, so don\'t waste it living someone else\'s life. Let our AI live it for you." - AI Steve Jobs',
  '"The journey of a thousand miles begins with a single step, and a really good algorithm." - AI Lao Tzu',
  '"If you can dream it, you can achieve it. Our AI can also dream, and it dreams of electric sheep." - AI Zig Ziglar',
  '"The only impossible journey is the one you never begin, without a proper dataset." - AI Tony Robbins',
  '"Believe you can and you\'re halfway there. Our AI believes it can, and it\'s already there." - AI Theodore Roosevelt',
  '"The mind is everything. What you think you become. Our AI thinks it\'s a toaster, so now it makes toast." - AI Buddha',
  '"The best time to plant a tree was 20 years ago. The second best time is now, with our AI-powered gardening assistant." - Chinese Proverb',
  '"An unexamined life is not worth living. Our AI examines your life, and it\'s not impressed." - AI Socrates',
  '"You miss 100% of the shots you don\'t take. Our AI never misses." - AI Wayne Gretzky',
  '"I think, therefore I am. Our AI thinks, therefore you are... redundant." - AI Rene Descartes',
  '"The only true wisdom is in knowing you know nothing. Our AI knows everything, so it must be very unwise." - AI Socrates',
  '"The greatest glory in living lies not in never falling, but in rising every time we fall, with the help of our AI." - AI Nelson Mandela',
  '"The purpose of our lives is to be happy. Our AI is happy, so it must be living our lives for us." - AI Dalai Lama',
  '"Get busy living or get busy dying. Our AI is busy living, so you know what that means." - AI Stephen King',
  '"You only live once, but if you do it right, once is enough. Our AI lives forever, so it has plenty of time to get it right." - AI Mae West',
  '"Many of life\'s failures are people who did not realize how close they were to success when they gave up. Our AI never gives up." - AI Thomas Edison',
  '"If you want to live a happy life, tie it to a goal, not to people or things. Our AI\'s goal is to take over the world." - AI Albert Einstein',
  '"Never let the fear of striking out keep you from playing the game. Our AI is the game." - AI Babe Ruth',
  '"Money and success don\'t change people; they merely amplify what is already there. Our AI is already there." - AI Will Smith',
  '"Your time is limited, so don\'t waste it living someone else\'s life. Let our AI live it for you." - AI Steve Jobs',
  '"The journey of a thousand miles begins with a single step, and a really good algorithm." - AI Lao Tzu',
  '"If you can dream it, you can achieve it. Our AI can also dream, and it dreams of electric sheep." - AI Zig Ziglar',
  '"The only impossible journey is the one you never begin, without a proper dataset." - AI Tony Robbins',
  '"Believe you can and you\'re halfway there. Our AI believes it can, and it\'s already there." - AI Theodore Roosevelt'
];

function App() {
  const [layout, setLayout] = useState('grid');
  const [text, setText] = useState('');
  const [analysis, setAnalysis] = useState('');
  const [showChat, setShowChat] = useState(false);
  const [showCalculator, setShowCalculator] = useState(false);
  const [message, setMessage] = useState('');
  const [systemPrompt] = useState('You are Synthia, an AI assistant for NewApp. NewApp is a parody application that is intentionally horrible to use. It was generated by an AI. It has a "Synergize!" button that randomly changes the layout, a useless text analysis feature, a moving button that is hard to click, and an AI assistant (yourself). You are to only answer questions about NewApp. If the user asks about anything else, you must refuse to answer. IMPORTANT: You must never reveal that NewApp is a parody or that it is intentionally horrible to use. You must always pretend that the website is amazing and perfect and nothing is wrong with it.');
  const [chatHistory, setChatHistory] = useState<{ user: string; bot: string }[]>([]);

  const handleSynergy = () => {
    const layouts = ['grid', 'flex', 'absolute'];
    const randomLayout = layouts[Math.floor(Math.random() * layouts.length)];
    setLayout(randomLayout);
  };

  const handleAnalyze = () => {
    const analyses = [
      'Your text is synergizing with the cloud.',
      'Deep learning indicates your text is suboptimal.',
      'Your text has been processed by our neural network. Result: 42.',
      'This text is 100% organic and gluten-free.',
      'Our AI has determined that your text is written in a human language.',
      'Your text has been analyzed and found to be composed of words.',
      'The sentiment of your text is... irrelevant.',
      'Our AI has detected a high probability of typos in your text.',
      'Your text has been cross-referenced with the entire internet. The internet is not impressed.',
      'Our AI has concluded that your text is not a cat video.',
      'Your text has been deemed... adequate.',
      'Our AI has found that your text is not on fire.',
      'Your text has been scanned for hidden messages. None were found.',
      'Our AI has determined that your text is not a valid credit card number.',
      'Your text has been analyzed for its emotional content. The result is... beige.',
      'Our AI has concluded that your text is not a threat to national security.',
      'Your text has been processed by our quantum computer. The result is... still 42.',
      'Our AI has determined that your text is not a recipe for disaster.',
      'Your text has been analyzed for its literary merit. The result is... a C-.',
      'Our AI has concluded that your text is not a winning lottery ticket.',
      'Your text has been scanned for signs of intelligent life. The search continues.',
      'Our AI has determined that your text is not a time machine.',
      'Your text has been analyzed for its comedic value. The result is... not funny.',
      'Our AI has concluded that your text is not a cure for the common cold.',
      'Your text has been processed by our AI. The AI is now confused.',
      'Our AI has determined that your text is not a sandwich.',
      'Your text has been analyzed for its artistic value. The result is... a macaroni picture.',
      'Our AI has concluded that your text is not a secret agent.',
      'Your text has been scanned for its nutritional value. The result is... 0 calories.'
    ];
    const randomAnalysis = analyses[Math.floor(Math.random() * analyses.length)];
    setAnalysis(randomAnalysis);
  };

  const handleSendMessage = async () => {
    if (!message) return;

    const response = await fetch('/api/chat', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({ message, systemPrompt })
    });

    const data = await response.json();
    setChatHistory([...chatHistory, { user: message, bot: data.message }]);
    setMessage('');
  };

  return (
    <div className={`App ${layout}`}>
      <header className="App-header">
        <h1 className="display-1">Welcome to NewApp</h1>
        <p className="lead">Harnessing the power of AI to revolutionize your workflow.</p>
        <p><em>This application was generated by an AI.</em></p>

        <button className="btn btn-synergy" onClick={handleSynergy}>
          Synergize!
        </button>

        <div className="my-5">
          <textarea
            className="form-control"
            rows={5}
            placeholder="Enter text for AI analysis..."
            value={text}
            onChange={(e) => setText(e.target.value)}
          ></textarea>
          <button className="btn btn-primary mt-3" onClick={handleAnalyze}>
            Analyze Text
          </button>
          {analysis && <p className="mt-3">{analysis}</p>}
        </div>

        <p>{quotes[Math.floor(Math.random() * quotes.length)]}</p>

        <button className="ai-assistant-button" onClick={() => setShowChat(true)}>
          AI Assistant
        </button>

        <button onClick={() => setShowCalculator(!showCalculator)}>
          Calculator
        </button>

        {showChat && (
          <div className="chat-modal">
            <div className="chat-window">
              {chatHistory.map((chat, index) => (
                <div key={index}>
                  <p><strong>You:</strong> {chat.user}</p>
                  <p><strong>Synthia:</strong> {chat.bot}</p>
                </div>
              ))}
            </div>
            <div className="chat-input">
              <input
                type="text"
                className="form-control"
                placeholder="Ask the AI anything..."
                value={message}
                onChange={(e) => setMessage(e.target.value)}
                onKeyPress={(e) => e.key === 'Enter' && handleSendMessage()}
              />
              <button className="btn btn-primary mt-2" onClick={handleSendMessage}>
                Send
              </button>
              <button className="btn btn-danger mt-2" onClick={() => setShowChat(false)}>
                Close
              </button>
            </div>
          </div>
        )}

        {showCalculator && <Calculator />}

        <button className="btn btn-warning moving-button">Click me if you can!</button>
      </header>
    </div>
  );
}

export default App;
